### ISSUE TITLE
Sum of input lengths does not equal the length of the input dataset

### ISSUE THREAD

**Issue by xfx0324** [aks2203/easy-to-hard#3]
Hi, Nice work! but when I try to run 
```
cd prefix_sums
./launch/train_models.sh
```
I got errors:

```
20210715 18:27:16 train.py main() running.
checkpoint: checkpoints/recur
clip: 1.0
data_path: ../data
debug: False
depth: 44
epochs: 500
eval_data: 30
json_name: test_stats
lr: 0.001
lr_decay: step
lr_factor: 0.5
lr_schedule: [100, 200, 300]
model: recur_net
model_path: None
shuffle: True
optimizer: adam
output: results/train_on_32_bit
save_json: True
save_period: 20
test_batch_size: 500
test_iterations: None
test_mode: default
train_batch_size: 150
train_data: 32
train_log: recur_44_1.txt
train_mode: xent_clipped
train_split: 0.8
val_period: 5
warmup_period: 10
width: 120
logging done in results/train_on_32_bit.
Files already downloaded and verified
Loading data with 32 bits.
Files already downloaded and verified
Loading data with 30 bits.
Traceback (most recent call last):
  File "train.py", line 252, in <module>
    main()
  File "train.py", line 97, in main
    args.eval_data, args.train_split, shuffle=args.shuffle)
  File "/Users/chris/work/easy-to-hard/prefix_sums/utils.py", line 57, in get_dataloaders
    generator=torch.Generator().manual_seed(42))
  File "/anaconda3/envs/easy2hard/lib/python3.7/site-packages/torch/utils/data/dataset.py", line 293, in random_split
    raise ValueError("Sum of input lengths does not equal the length of the input dataset!")
```

how to resolve this?
Environments:

```
conda create -n easy2hard python=3.7 
Python 3.7.10
```

**Comment by aks2203** [comment]
Hi, thanks for pointing this out. I was able to reproduce the error locally. I think the most recent two commits should have fixed this issue. Please try again with the latest version and let me know. 
Commits: 03436ad116173cd5e5b05763f239a252db7d8267 and 54d8933279ae340deed5078cb0b3253c2ee1ee1f

**Comment by xfx0324** [comment]
thanks ! fixed indeed
